name: Build
run-name: build by ${{ github.actor }}

on:
  workflow_dispatch:
  push:

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

env:
  GCP_PROJECT_NAME: triple-nectar-391006
  GCP_SERVICE_ACCOUNT_NAME: github-actions-workflow
  GCP_WORKLOAD_IDENTITY: projects/435965541776/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
  GKE_CLUSTER_NAME: applications
  GKE_CLUSTER_ZONE: europe-west1-b
  DOCKER_RGSTR_REGION: europe-west1
  DOCKER_RGSTR_NAME: docker-registry

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v0'
      with:
        create_credentials_file: true
        token_format: access_token
        workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY }}
        service_account: ${{ env.GCP_SERVICE_ACCOUNT_NAME }}@${{ env.GCP_PROJECT_NAME }}.iam.gserviceaccount.com

    - name: Connect to Artifact Registry
      run: |-
        echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin https://${{ env.DOCKER_RGSTR_REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_RGSTR_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_NAME }}/${{ env.DOCKER_RGSTR_NAME }}/pyapp:latest pyapp

    - name: Publish Docker image to Google Artifact Registry
      run: docker push ${{ env.DOCKER_RGSTR_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_NAME }}/${{ env.DOCKER_RGSTR_NAME }}/pyapp:latest

    - name: Connect to GKE
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER_NAME }}
        location: ${{ env.GKE_CLUSTER_ZONE }}

    - name: Deploy to GKE
      run: kubectl apply -f pyapp/deployment.yaml
