name: Build
run-name: build by ${{ github.actor }}

on:
  workflow_dispatch:
  push:

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

env:
  GCP_PROJECT_ID: triple-nectar-391006
  GCP_REGION: europe-west1
  GKE_CLUSTER_NAME: applications
  GKE_CLUSTER_ZONE: europe-west1-b
  GCP_WORKFLOW_SA: github-actions-workflow@triple-nectar-391006.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY: projects/435965541776/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
  DOCKER_REGISTRY_NAME: docker-registry
  APP_NAME: pyapp

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v0'
      with:
        create_credentials_file: true
        token_format: access_token
        workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY }}
        service_account: ${{ env.GCP_WORKFLOW_SA }}

    - name: Set Docker registry host
      run: echo "DOCKER_REGISTRY_HOST=${{ env.GCP_REGION }}-docker.pkg.dev" >> $GITHUB_ENV

    - name: Connect to Artifact Registry
      run: |-
        echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin https://${{ env.DOCKER_REGISTRY_HOST }}

    - name: Set Docker image tag
      run: echo "IMAGE_TAG=${{ env.DOCKER_REGISTRY_HOST }}/${{ env.GCP_PROJECT_ID }}/${{ env.DOCKER_REGISTRY_NAME }}/${{ env.APP_NAME }}:$GITHUB_SHA" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_TAG }} ${{ env.APP_NAME }}

    - name: Publish Docker image to Google Artifact Registry
      run: docker push ${{ env.IMAGE_TAG }}

    - name: Connect to GKE
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER_NAME }}
        location: ${{ env.GKE_CLUSTER_ZONE }}

    - name: Set new docker image version in deployment.yaml
      run: sed -i 's|APP_DOCKER_IMAGE|${{ env.IMAGE_TAG }}|g' pyapp/deployment.yaml

    - name: Deploy to GKE
      run: kubectl apply -f pyapp/deployment.yaml
